CREATE TABLE requests (
    id BIGSERIAL PRIMARY KEY,
    created TIMESTAMPTZ default now(),
    sender BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    reciever BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE friends (
    id BIGSERIAL PRIMARY KEY,
    user_a BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    friend_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL
);